import { cx } from "@/lib/cx"

/**
 * Hand-drawn icons, authored as paths rather than generated by rough.js.
 *
 * rough.js's randomness is a fixed number of pixels, so at icon scale the wobble
 * is the entire drawing and a 14px arrow comes out as a smudge. These are drawn
 * by hand instead -- deliberately a little off-square -- and stay crisp at the
 * size they are used.
 */
const PATHS = {
  down: ["M8 3.2c-.06 3.2-.11 6.3-.16 9.7", "M4.15 8.85c1.3 1.42 2.55 2.8 3.8 4.2 1.22-1.42 2.4-2.78 3.92-4.2"],
  up: ["M8 12.9c.06-3.2.11-6.3.16-9.7", "M4.15 7.15c1.3-1.42 2.55-2.8 3.8-4.2 1.22 1.42 2.4 2.78 3.92 4.2"],
  sun: [
    "M8 4.6c1.9-.06 3.4 1.5 3.42 3.4 0 1.9-1.5 3.4-3.4 3.42-1.9 0-3.44-1.5-3.42-3.4C4.6 6.1 6.1 4.55 8 4.6Z",
    "M8 1.35v1.95",
    "M8 12.7v1.95",
    "M1.35 8h1.95",
    "M12.7 8h1.95",
    "M3.4 3.4l1.35 1.35",
    "M11.25 11.25l1.38 1.35",
    "M12.6 3.4l-1.35 1.35",
    "M4.75 11.25 3.4 12.6",
  ],
  moon: ["M14 8.53A6 6 0 1 1 7.47 2A4.67 4.67 0 0 0 14 8.53Z"],
  back: ["M9.75 3.3 5.35 7.95l4.5 4.7"],
  clock: [
    "M8 2.3c3.1-.05 5.7 2.5 5.72 5.7 0 3.2-2.55 5.7-5.7 5.72C4.8 13.7 2.3 11.2 2.28 8 2.3 4.85 4.85 2.32 8 2.3Z",
    "M8 4.85v3.4l2.5 1.55",
  ],
  alert: [
    "M8 2.6c.5-.9 1.75-.9 2.25 0l4.4 7.6c.5.9-.15 2-1.15 2H2.5c-1 0-1.65-1.1-1.15-2Z",
    "M8 6.4v3.1",
    "M8 11.5v.6",
  ],
  refresh: ["M13.3 8a5.3 5.3 0 1 1-1.6-3.8", "M13.6 2.6v3.5h-3.4"],
  server: [
    "M3.2 3.1h9.6c.5 0 .9.4.9.9v2c0 .5-.4.9-.9.9H3.2c-.5 0-.9-.4-.9-.9v-2c0-.5.4-.9.9-.9Z",
    "M3.2 9.1h9.6c.5 0 .9.4.9.9v2c0 .5-.4.9-.9.9H3.2c-.5 0-.9-.4-.9-.9v-2c0-.5.4-.9.9-.9Z",
    "M4.6 5h.5",
    "M4.6 11h.5",
  ],
  // Traffic both ways: one line out, one line back, each with its head. A pair
  // of chain links was tried first and read as a tangle -- two curves
  // overlapping in the middle leave the eye no edge to land on at 16px.
  network: [
    "M2.6 5.7c2.5-.05 5-.05 7.5 0",
    "M8.45 4.15 10.1 5.7 8.45 7.25",
    "M13.4 10.3c-2.5-.05-5-.05-7.5 0",
    "M7.55 8.75 5.9 10.3 7.55 11.85",
  ],
  // Three arcs off one foot, as a signal is drawn on paper. The rise is kept at
  // 0.22 of each chord so the three stay concentric instead of fanning out.
  probe: [
    "M8 11.65c.45-.02.8.35.78.78-.02.43-.36.77-.78.78-.43.02-.8-.33-.78-.78.02-.43.36-.76.78-.78Z",
    "M5.7 10.45c1.2-1.33 3.4-1.33 4.6 0",
    "M3.7 8.8c2.25-2.55 6.35-2.55 8.6 0",
    "M1.7 7.15c3.3-3.75 9.3-3.75 12.6 0",
  ],
  // A platter stack, seen slightly from above: the top face, the body, and the
  // activity lamp on the front.
  disk: [
    "M8 3c2.85 0 5.15 1.05 5.15 2.35S10.85 7.7 8 7.7 2.85 6.65 2.85 5.35 5.15 3 8 3Z",
    "M2.85 5.35v5.3c0 1.3 2.3 2.35 5.15 2.35s5.15-1.05 5.15-2.35v-5.3",
    "M5.5 11.1c.22-.02.4.17.38.38-.02.22-.19.38-.38.38-.22.02-.4-.17-.38-.38.02-.22.19-.38.38-.38Z",
  ],
  // A memory stick: the module, and the three contact pins under it.
  ram: [
    "M3.4 5.1h9.2c.45 0 .8.35.8.8v3.3c0 .45-.35.8-.8.8H3.4c-.45 0-.8-.35-.8-.8V5.9c0-.45.35-.8.8-.8Z",
    "M5.4 9.95c.02.4.02.78.04 1.18",
    "M8 9.95c.02.4.02.78.04 1.18",
    "M10.6 9.95c.02.4.02.78.04 1.18",
  ],
  // A grouping bracket, open to the right: the mark put beside a run of lines
  // to say they belong together.
  bracket: [
    "M6.4 3.3c-1.55.05-2.4.45-2.4 1.7v1.9c0 1-.5 1.4-1.75 1.65 1.25.25 1.75.65 1.75 1.65v1.9c0 1.25.85 1.65 2.4 1.7",
  ],
  // A note, with the fold at the top right and two lines of writing. The body
  // is washed (see WASH below) so it reads as a sheet of paper rather than as
  // an empty box.
  note: [
    "M3.6 2.8h5.95l3.85 3.85v5.65c0 .5-.4.9-.9.9H3.6c-.5 0-.9-.4-.9-.9V3.7c0-.5.4-.9.9-.9Z",
    "M9.55 2.8v3.85h3.85",
    "M5.1 8.7c1.8-.05 3.6-.05 5.4 0",
    "M5.1 11c1.2-.05 2.4-.05 3.6 0",
  ],
  // A link that has come apart: the two ends stopped short of each other, with
  // a cross in the gap. The gap is wide on purpose -- at 12px the round caps
  // close a narrower one and the whole mark fills in as a single smudged dash.
  timeout: [
    "M1.7 8.05c.8-.05 1.6-.05 2.4 0",
    "M14.3 7.95c-.8.05-1.6.05-2.4 0",
    "M6.2 6.2c1.2 1.2 2.4 2.4 3.6 3.6",
    "M9.8 6.2c-1.2 1.2-2.4 2.4-3.6 3.6",
  ],
  // A dial: the half-round scale, the needle, and the pivot it turns on.
  gauge: [
    "M2.7 11.95c0-2.95 2.35-5.35 5.3-5.35 2.95 0 5.3 2.4 5.3 5.35",
    "M8 11.9c1.05-1.25 2.1-2.55 3.15-3.85",
    "M8 11.35c.3-.02.55.22.53.52-.02.3-.25.5-.53.5-.3.02-.55-.22-.53-.52.02-.3.25-.5.53-.5Z",
  ],
} as const

/**
 * Paths that are a filled body rather than a line, and are washed behind their
 * own strokes. Tinted with the icon's colour rather than with `--hatch`: a card
 * is already shaded in `--hatch`, so a note drawn on one would come out with no
 * shading at all. Kept to one icon -- a wash on every symbol turns a row of
 * icons into a row of grey blobs at this size.
 */
const WASH: Partial<Record<IconName, readonly number[]>> = { note: [0] }

export type IconName = keyof typeof PATHS

export function Icon({ name, size = 16, className }: { name: IconName; size?: number; className?: string }) {
  const washed = WASH[name]
  return (
    <svg
      className={cx("icon", className)}
      width={size}
      height={size}
      viewBox="0 0 16 16"
      fill="none"
      aria-hidden="true"
      focusable="false"
    >
      {PATHS[name].map((d, i) => (
        <path
          key={i}
          d={d}
          stroke="currentColor"
          strokeWidth={1.5}
          strokeLinecap="round"
          strokeLinejoin="round"
          fill={washed?.includes(i) ? "currentColor" : "none"}
          fillOpacity={washed?.includes(i) ? 0.13 : undefined}
        />
      ))}
    </svg>
  )
}
